config/routes.rb
Rails.application.routes.draw do
  # jobs monitor

  authenticate :user do
    mount MissionControl::Jobs::Engine, at: "/tareas"
  end

  devise_for :users
  resources :articles do
    member do
      patch :publish
      patch :unpublish
    end
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "articles#index"

  get "session/status", to: "sessions#status"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :body

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  enum :publication_state, draft: 0, published: 1
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user, inverse_of: :comments, required: true

  broadcasts_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :comments, inverse_of: :user
  has_many :articles, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "No tienes permiso para realizar esta acción."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy publish unpublish]
  before_action :authenticate_user!, only: %i[ edit update destroy publish unpublish]
  before_action :authorize_article, only: %i[ edit update destroy publish unpublish]

  # GET /articles or /articles.json
  def index
    # @articles = Article.all.order(created_at: :desc)
    @articles = policy_scope(Article).order(created_at: :desc) # Aplica la política de visibilidad

    # Si se envía un parámetro de búsqueda, filtramos por título o cuerpo
    if params[:query].present?
      query = "%#{params[:query]}%"
      @articles = @articles.where("title LIKE ?", query)
      # articles = articles.where("title LIKE ? OR body LIKE ?", query, query)
    end

    @articles = @articles.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    authorize Article
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    authorize Article
    @article = Article.new(article_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def publish
    authorize @article  # Autoriza la acción 'publish'

    if @article.update(publication_state: :published)
      redirect_to @article, notice: "Artículo publicado con éxito."
    else
      redirect_to @article, alert: "No se pudo publicar el artículo."
    end
  end

  def unpublish
    authorize @article  # Autoriza la acción 'unpublish'

    if @article.update(publication_state: :draft)
      redirect_to @article, notice: "Artículo vuelto a borrador."
    else
      redirect_to @article, alert: "No se pudo cambiar el estado del artículo."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.expect(article: [ :title, :body ])
    end

    # Authorize the article actions
    def authorize_article
      authorize @article
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    # Crear el comentario asociado al usuario logueado
    @comment = @article.comments.create(comment_params.merge(user_id: current_user.id))
    # @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def status
    render json: { logged_in: user_signed_in? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate_html(content, length = 150)
    sanitized_content = sanitize(content.to_s) # Limpia HTML para evitar scripts maliciosos
    truncated_content = truncate(strip_tags(sanitized_content), length: length)
    truncated_content.html_safe # Permite volver a renderizar como HTML seguro
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="article-container">
  <% if user_signed_in? %>
    <div class="status-label <%= article.draft? ? 'status-draft' : 'status-published' %>">
      <%= article.draft? ? '📝 Draft' : '✅ Published' %>
    </div>
  <% end %>  
  <p>
    <strong>Por:</strong>
    <%= article.user.email %>
  </p>
  <div class="article-title">
    <h2>
      <strong>Title:</strong>
      <%= article.title %>
    </h2>
  </div>  
  <p>
    <strong>Body:</strong>
    <% if local_assigns[:truncate_content] %>
      <%= truncate(article.body.to_plain_text, length: 150) %>
    <% else %>
      <%= article.body %>
    <% end %>
    <% if local_assigns[:truncate_content] %>
      <a href="<%= article_path(article) %>" class="read-more">Leer más</a>
    <% end %>
  </p>
  <p>
    <%= button_to "Show this article", article_path(article), method: :get, class: "btn btn-primary" %>
  </p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title, "Editando artículo" %>

<h1>Editando artículo</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Mostrar este artículo", @article %> |
  <%= link_to "Volver al listado de artículos", articles_path %>
</div>

app/views/articles/index.html.erb
<% content_for :title, "Articles" %>

<h1>Artículos</h1>

<%= form_with url: articles_path, method: :get, data: { turbo_frame: "articles" } do %>
  <div class="mb-3">
    <%= label_tag :query, "Buscar:" %>
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Buscar artículos..." %>
  </div>
  <%= submit_tag "Buscar", class: "btn btn-secondary" %>
<% end %>

<turbo-frame id="articles">
  <%= render partial: "articles/article", collection: @articles, as: :article, locals: { truncate_content: true } %>

  <!-- Enlaces de paginación -->
  <div class="pagination-container">
    <%= paginate @articles %>
  </div>

  <!-- Información de la paginación -->
  <% if @articles.any? %>
    <%# Calculamos el primer y último índice de la página actual %>
    <% start_index = (@articles.current_page - 1) * @articles.limit_value + 1 %>
    <% end_index = [start_index + @articles.limit_value - 1, @articles.total_count].min %>
    <p class="pagination-info">
      Mostrando <%= start_index %> - <%= end_index %> de <%= @articles.total_count %> artículos.
    </p>
  <% else %>
    <p>No se encontraron artículos</p>
  <% end %>
</turbo-frame>

<%= button_to "Nuevo artículo", new_article_path, method: :get, class: "btn btn-primary" %>

app/views/articles/new.html.erb
<% content_for :title, "Nuevo artículo" %>

<h1>Nuevo artículo</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Volver al listado de artículos", articles_path %>
</div>

app/views/articles/show.html.erb
<turbo-frame id="articles">
  <%= render @article %>

  <div class="button-group">
    <% if user_signed_in? %>
      <% if @article.user == current_user %>
        <%= button_to "Edit this article", edit_article_path(@article), method: :get, class: "btn btn-primary" %>
        <%= button_to "Destroy this article", @article, method: :delete, class: "btn btn-danger" %>
        <% if @article.publication_state == 'draft' %>
          <%= button_to "Publish this article", publish_article_path(@article), method: :patch, class: "btn btn-success" %>
        <% else %>
          <%= button_to "Unpublish this article", unpublish_article_path(@article), method: :patch, class: "btn btn-warning" %>
        <% end %>
      <% else %>
        <%= button_to "Edit this article", edit_article_path(@article), method: :get, class: "btn btn-disabled" %>
        <%= button_to "Destroy this article", @article, method: :delete, class: "btn btn-disabled" %>
        <% if @article.publication_state == 'draft' %>
          <%= button_to "Publish this article", publish_article_path(@article), method: :patch, class: "btn btn-disabled" %>
        <% else %>
          <%= button_to "Unpublish this article", unpublish_article_path(@article), method: :patch, class: "btn btn-disabled" %>
        <% end %>
      <% end %>
    <% end %>
    
    <%= button_to "Volver al listado de artículos", articles_path, method: :get, class: "btn btn-secondary" %>
  </div>

  <hr class="my-4">

  <h4> Comentarios: </h4>
  <div class="comments-container">
    <%= render @article.comments %>
  </div>  

  <h4>Agregar un comentario:</h4>
  <%= render "comments/form", article: @article %>
</turbo-frame>

app/views/comments/_comment.html.erb
<div class="comment">
    <p>
        <strong>Usuario:</strong>
        <%= comment.user.email %>
    </p>    

    <p>
        <strong>Comentario:</strong>
        <%= comment.body %>
    </p>
    <p>
        <strong>Updated at:</strong>
        <%= time_tag comment.updated_at, 
        "data-local": "time", 
        "data-format": "%-d de %B %H:%M" %>
    </p>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title><%= content_for(:title) || "Blog 4" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <% if user_signed_in? %>
          <!-- Mostrar correo y botón de cerrar sesión -->
          <span>Bienvenido, <%= current_user.email %></span>
          <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-logout" %>
        <% else %>
          <!-- Mostrar botón de iniciar sesión -->
          <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-login" %>
        <% end %>
      </nav>
    </header>

    <main>
      <% if flash.any? %>
        <div class="flash-messages">
          <% flash.each do |key, message| %>
            <div class="alert <%= key %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <p>&copy; 2024 Mi Aplicación</p>
    </footer>
  </body>
</html>